"""create exercises workouts and workout exercises

Revision ID: c548347395e7
Revises: 
Create Date: 2026-09-26 12:40:26.144479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c548347395e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('strength', 'cardio', 'flexibility', 'balance')", name='ck_exercises_category'),
    sa.CheckConstraint('length(name) >= 1 AND length(name) <= 80', name='ck_exercises_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_exercises_name')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes >= 1 AND duration_minutes <= 300', name='ck_workouts_duration_minutes'),
    sa.CheckConstraint('notes IS NULL OR (length(notes) >= 1 AND length(notes) <= 500)', name='ck_workouts_notes_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_seconds >= 1 AND duration_seconds <= 7200', name='ck_workout_exercises_duration_seconds'),
    sa.CheckConstraint('reps >= 1 AND reps <= 100', name='ck_workout_exercises_reps'),
    sa.CheckConstraint('sets >= 1 AND sets <= 50', name='ck_workout_exercises_sets'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
